default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gin_react_development

test:
  <<: *default
  database: gin_react_test

production:
  <<: *default
  database: gin_react_production

